import { Injectable } from '@angular/core';
import { title, code } from './interfaces';

@Injectable()
export class Globals {
    
    titles: Array<title> = [{id: 1, value: 'Mr.'},{id: 2, value: 'Ms.'},{id: 3, value: 'Dr.'},{id: 4, value: 'Prof.'},{id: 5, value: 'Other'}]; 
    codes: Array<code> = [
        {countryCode: 'LB' , value: '+961', desc: 'Lebanon (+961)'},
        {countryCode: 'US' , value: '+1', desc: 'USA (+1)'},
        {countryCode: 'DZ' , value: '+213', desc: 'Algeria (+213)'},
        {countryCode: 'AD' , value: '+376', desc: 'Andorra (+376)'},
        {countryCode: 'AO' , value: '+244', desc: 'Angola (+244)'},
        {countryCode: 'AI' , value: '+1264', desc: 'Anguilla (+1264)'},
        {countryCode: 'AG' , value: '+1268', desc: 'Antigua &amp; Barbuda (+1268)'},
        {countryCode: 'AR' , value: '+54', desc: 'Argentina (+54)'},
        {countryCode: 'AM' , value: '+374', desc: 'Armenia (+374)'},
        {countryCode: 'AW' , value: '+297', desc: 'Aruba (+297)'},
        {countryCode: 'AU' , value: '+61', desc: 'Australia (+61)'},
        {countryCode: 'AT' , value: '+43', desc: 'Austria (+43)'},
        {countryCode: 'AZ' , value: '+994', desc: 'Azerbaijan (+994)'},
        {countryCode: 'BS' , value: '+1242', desc: 'Bahamas (+1242)'},
        {countryCode: 'BH' , value: '+973', desc: 'Bahrain (+973)'},
        {countryCode: 'BD' , value: '+880', desc: 'Bangladesh (+880)'},
        {countryCode: 'BB' , value: '+1246', desc: 'Barbados (+1246)'},
        {countryCode: 'BY' , value: '+375', desc: 'Belarus (+375)'},
        {countryCode: 'BE' , value: '+32', desc: 'Belgium (+32)'},
        {countryCode: 'BZ' , value: '+501', desc: 'Belize (+501)'},
        {countryCode: 'BJ' , value: '+229', desc: 'Benin (+229)'},
        {countryCode: 'BM' , value: '+1441', desc: 'Bermuda (+1441)'},
        {countryCode: 'BT' , value: '+975', desc: 'Bhutan (+975)'},
        {countryCode: 'BO' , value: '+591', desc: 'Bolivia (+591)'},
        {countryCode: 'BA' , value: '+387', desc: 'Bosnia Herzegovina (+387)'},
        {countryCode: 'BW' , value: '+267', desc: 'Botswana (+267)'},
        {countryCode: 'BR' , value: '+55', desc: 'Brazil (+55)'},
        {countryCode: 'BN' , value: '+673', desc: 'Brunei (+673)'},
        {countryCode: 'BG' , value: '+359', desc: 'Bulgaria (+359)'},
        {countryCode: 'BF' , value: '+226', desc: 'Burkina Faso (+226)'},
        {countryCode: 'BI' , value: '+257', desc: 'Burundi (+257)'},
        {countryCode: 'KH' , value: '+855', desc: 'Cambodia (+855)'},
        {countryCode: 'CM' , value: '+237', desc: 'Cameroon (+237)'},
        {countryCode: 'CA' , value: '+1', desc: 'Canada (+1)'},
        {countryCode: 'CV' , value: '+238', desc: 'Cape Verde Islands (+238)'},
        {countryCode: 'KY' , value: '+1345', desc: 'Cayman Islands (+1345)'},
        {countryCode: 'CF' , value: '+236', desc: 'Central African Republic (+236)'},
        {countryCode: 'CL' , value: '+56', desc: 'Chile (+56)'},
        {countryCode: 'CN' , value: '+86', desc: 'China (+86)'},
        {countryCode: 'CO' , value: '+57', desc: 'Colombia (+57)'},
        {countryCode: 'KM' , value: '+269', desc: 'Comoros (+269)'},
        {countryCode: 'CG' , value: '+242', desc: 'Congo (+242)'},
        {countryCode: 'CK' , value: '+682', desc: 'Cook Islands (+682)'},
        {countryCode: 'CR' , value: '+506', desc: 'Costa Rica (+506)'},
        {countryCode: 'HR' , value: '+385', desc: 'Croatia (+385)'},
        {countryCode: 'CU' , value: '+53', desc: 'Cuba (+53)'},
        {countryCode: 'CY' , value: '+90392', desc: 'Cyprus North (+90392)'},
        {countryCode: 'CY' , value: '+357', desc: 'Cyprus South (+357)'},
        {countryCode: 'CZ' , value: '+42', desc: 'Czech Republic (+42)'},
        {countryCode: 'DK' , value: '+45', desc: 'Denmark (+45)'},
        {countryCode: 'DJ' , value: '+253', desc: 'Djibouti (+253)'},
        {countryCode: 'DM' , value: '+1809', desc: 'Dominica (+1809)'},
        {countryCode: 'DO' , value: '+1809', desc: 'Dominican Republic (+1809)'},
        {countryCode: 'EC' , value: '+593', desc: 'Ecuador (+593)'},
        {countryCode: 'EG' , value: '+20', desc: 'Egypt (+20)'},
        {countryCode: 'SV' , value: '+503', desc: 'El Salvador (+503)'},
        {countryCode: 'GQ' , value: '+240', desc: 'Equatorial Guinea (+240)'},
        {countryCode: 'ER' , value: '+291', desc: 'Eritrea (+291)'},
        {countryCode: 'EE' , value: '+372', desc: 'Estonia (+372)'},
        {countryCode: 'ET' , value: '+251', desc: 'Ethiopia (+251)'},
        {countryCode: 'FK' , value: '+500', desc: 'Falkland Islands (+500)'},
        {countryCode: 'FO' , value: '+298', desc: 'Faroe Islands (+298)'},
        {countryCode: 'FJ' , value: '+679', desc: 'Fiji (+679)'},
        {countryCode: 'FI' , value: '+358', desc: 'Finland (+358)'},
        {countryCode: 'FR' , value: '+33', desc: 'France (+33)'},
        {countryCode: 'GF' , value: '+594', desc: 'French Guiana (+594)'},
        {countryCode: 'PF' , value: '+689', desc: 'French Polynesia (+689)'},
        {countryCode: 'GA' , value: '+241', desc: 'Gabon (+241)'},
        {countryCode: 'GM' , value: '+220', desc: 'Gambia (+220)'},
        {countryCode: 'GE' , value: '+7880', desc: 'Georgia (+7880)'},
        {countryCode: 'DE' , value: '+49', desc: 'Germany (+49)'},
        {countryCode: 'GH' , value: '+233', desc: 'Ghana (+233)'},
        {countryCode: 'GI' , value: '+350', desc: 'Gibraltar (+350)'},
        {countryCode: 'GR' , value: '+30', desc: 'Greece (+30)'},
        {countryCode: 'GL' , value: '+299', desc: 'Greenland (+299)'},
        {countryCode: 'GD' , value: '+1473', desc: 'Grenada (+1473)'},
        {countryCode: 'GP' , value: '+590', desc: 'Guadeloupe (+590)'},
        {countryCode: 'GU' , value: '+671', desc: 'Guam (+671)'},
        {countryCode: 'GT' , value: '+502', desc: 'Guatemala (+502)'},
        {countryCode: 'GN' , value: '+224', desc: 'Guinea (+224)'},
        {countryCode: 'GW' , value: '+245', desc: 'Guinea - Bissau (+245)'},
        {countryCode: 'GY' , value: '+592', desc: 'Guyana (+592)'},
        {countryCode: 'HT' , value: '+509', desc: 'Haiti (+509)'},
        {countryCode: 'HN' , value: '+504', desc: 'Honduras (+504)'},
        {countryCode: 'HK' , value: '+852', desc: 'Hong Kong (+852)'},
        {countryCode: 'HU' , value: '+36', desc: 'Hungary (+36)'},
        {countryCode: 'IS' , value: '+354', desc: 'Iceland (+354)'},
        {countryCode: 'IN' , value: '+91', desc: 'India (+91)'},
        {countryCode: 'ID' , value: '+62', desc: 'Indonesia (+62)'},
        {countryCode: 'IR' , value: '+98', desc: 'Iran (+98)'},
        {countryCode: 'IQ' , value: '+964', desc: 'Iraq (+964)'},
        {countryCode: 'IE' , value: '+353', desc: 'Ireland (+353)'},
        {countryCode: 'IL' , value: '+972', desc: 'Israel (+972)'},
        {countryCode: 'IT' , value: '+39', desc: 'Italy (+39)'},
        {countryCode: 'JM' , value: '+1876', desc: 'Jamaica (+1876)'},
        {countryCode: 'JP' , value: '+81', desc: 'Japan (+81)'},
        {countryCode: 'JO' , value: '+962', desc: 'Jordan (+962)'},
        {countryCode: 'KZ' , value: '+7', desc: 'Kazakhstan (+7)'},
        {countryCode: 'KE' , value: '+254', desc: 'Kenya (+254)'},
        {countryCode: 'KI' , value: '+686', desc: 'Kiribati (+686)'},
        {countryCode: 'KP' , value: '+850', desc: 'Korea North (+850)'},
        {countryCode: 'KR' , value: '+82', desc: 'Korea South (+82)'},
        {countryCode: 'KW' , value: '+965', desc: 'Kuwait (+965)'},
        {countryCode: 'KG' , value: '+996', desc: 'Kyrgyzstan (+996)'},
        {countryCode: 'LA' , value: '+856', desc: 'Laos (+856)'},
        {countryCode: 'LV' , value: '+371', desc: 'Latvia (+371)'},
        {countryCode: 'LS' , value: '+266', desc: 'Lesotho (+266)'},
        {countryCode: 'LR' , value: '+231', desc: 'Liberia (+231)'},
        {countryCode: 'LY' , value: '+218', desc: 'Libya (+218)'},
        {countryCode: 'LI' , value: '+417', desc: 'Liechtenstein (+417)'},
        {countryCode: 'LT' , value: '+370', desc: 'Lithuania (+370)'},
        {countryCode: 'LU' , value: '+352', desc: 'Luxembourg (+352)'},
        {countryCode: 'MO' , value: '+853', desc: 'Macao (+853)'},
        {countryCode: 'MK' , value: '+389', desc: 'Macedonia (+389)'},
        {countryCode: 'MG' , value: '+261', desc: 'Madagascar (+261)'},
        {countryCode: 'MW' , value: '+265', desc: 'Malawi (+265)'},
        {countryCode: 'MY' , value: '+60', desc: 'Malaysia (+60)'},
        {countryCode: 'MV' , value: '+960', desc: 'Maldives (+960)'},
        {countryCode: 'ML' , value: '+223', desc: 'Mali (+223)'},
        {countryCode: 'MT' , value: '+356', desc: 'Malta (+356)'},
        {countryCode: 'MH' , value: '+692', desc: 'Marshall Islands (+692)'},
        {countryCode: 'MQ' , value: '+596', desc: 'Martinique (+596)'},
        {countryCode: 'MR' , value: '+222', desc: 'Mauritania (+222)'},
        {countryCode: 'YT' , value: '+269', desc: 'Mayotte (+269)'},
        {countryCode: 'MX' , value: '+52', desc: 'Mexico (+52)'},
        {countryCode: 'FM' , value: '+691', desc: 'Micronesia (+691)'},
        {countryCode: 'MD' , value: '+373', desc: 'Moldova (+373)'},
        {countryCode: 'MC' , value: '+377', desc: 'Monaco (+377)'},
        {countryCode: 'MN' , value: '+976', desc: 'Mongolia (+976)'},
        {countryCode: 'MS' , value: '+1664', desc: 'Montserrat (+1664)'},
        {countryCode: 'MA' , value: '+212', desc: 'Morocco (+212)'},
        {countryCode: 'MZ' , value: '+258', desc: 'Mozambique (+258)'},
        {countryCode: 'MN' , value: '+95', desc: 'Myanmar (+95)'},
        {countryCode: 'NA' , value: '+264', desc: 'Namibia (+264)'},
        {countryCode: 'NR' , value: '+674', desc: 'Nauru (+674)'},
        {countryCode: 'NP' , value: '+977', desc: 'Nepal (+977)'},
        {countryCode: 'NL' , value: '+31', desc: 'Netherlands (+31)'},
        {countryCode: 'NC' , value: '+687', desc: 'New Caledonia (+687)'},
        {countryCode: 'NZ' , value: '+64', desc: 'New Zealand (+64)'},
        {countryCode: 'NI' , value: '+505', desc: 'Nicaragua (+505)'},
        {countryCode: 'NE' , value: '+227', desc: 'Niger (+227)'},
        {countryCode: 'NG' , value: '+234', desc: 'Nigeria (+234)'},
        {countryCode: 'NU' , value: '+683', desc: 'Niue (+683)'},
        {countryCode: 'NF' , value: '+672', desc: 'Norfolk Islands (+672)'},
        {countryCode: 'NP' , value: '+670', desc: 'Northern Marianas (+670)'},
        {countryCode: 'NO' , value: '+47', desc: 'Norway (+47)'},
        {countryCode: 'OM' , value: '+968', desc: 'Oman (+968)'},
        {countryCode: 'PW' , value: '+680', desc: 'Palau (+680)'},
        {countryCode: 'PA' , value: '+507', desc: 'Panama (+507)'},
        {countryCode: 'PG' , value: '+675', desc: 'Papua New Guinea (+675)'},
        {countryCode: 'PY' , value: '+595', desc: 'Paraguay (+595)'},
        {countryCode: 'PE' , value: '+51', desc: 'Peru (+51)'},
        {countryCode: 'PH' , value: '+63', desc: 'Philippines (+63)'},
        {countryCode: 'PL' , value: '+48', desc: 'Poland (+48)'},
        {countryCode: 'PT' , value: '+351', desc: 'Portugal (+351)'},
        {countryCode: 'PR' , value: '+1787', desc: 'Puerto Rico (+1787)'},
        {countryCode: 'QA' , value: '+974', desc: 'Qatar (+974)'},
        {countryCode: 'RE' , value: '+262', desc: 'Reunion (+262)'},
        {countryCode: 'RO' , value: '+40', desc: 'Romania (+40)'},
        {countryCode: 'RU' , value: '+7', desc: 'Russia (+7)'},
        {countryCode: 'RW' , value: '+250', desc: 'Rwanda (+250)'},
        {countryCode: 'SM' , value: '+378', desc: 'San Marino (+378)'},
        {countryCode: 'ST' , value: '+239', desc: 'Sao Tome &amp; Principe (+239)'},
        {countryCode: 'SA' , value: '+966', desc: 'Saudi Arabia (+966)'},
        {countryCode: 'SN' , value: '+221', desc: 'Senegal (+221)'},
        {countryCode: 'CS' , value: '+381', desc: 'Serbia (+381)'},
        {countryCode: 'SC' , value: '+248', desc: 'Seychelles (+248)'},
        {countryCode: 'SL' , value: '+232', desc: 'Sierra Leone (+232)'},
        {countryCode: 'SG' , value: '+65', desc: 'Singapore (+65)'},
        {countryCode: 'SK' , value: '+421', desc: 'Slovak Republic (+421)'},
        {countryCode: 'SI' , value: '+386', desc: 'Slovenia (+386)'},
        {countryCode: 'SB' , value: '+677', desc: 'Solomon Islands (+677)'},
        {countryCode: 'SO' , value: '+252', desc: 'Somalia (+252)'},
        {countryCode: 'ZA' , value: '+27', desc: 'South Africa (+27)'},
        {countryCode: 'ES' , value: '+34', desc: 'Spain (+34)'},
        {countryCode: 'LK' , value: '+94', desc: 'Sri Lanka (+94)'},
        {countryCode: 'SH' , value: '+290', desc: 'St. Helena (+290)'},
        {countryCode: 'KN' , value: '+1869', desc: 'St. Kitts (+1869)'},
        {countryCode: 'SC' , value: '+1758', desc: 'St. Lucia (+1758)'},
        {countryCode: 'SD' , value: '+249', desc: 'Sudan (+249)'},
        {countryCode: 'SR' , value: '+597', desc: 'Suriname (+597)'},
        {countryCode: 'SZ' , value: '+268', desc: 'Swaziland (+268)'},
        {countryCode: 'SE' , value: '+46', desc: 'Sweden (+46)'},
        {countryCode: 'CH' , value: '+41', desc: 'Switzerland (+41)'},
        {countryCode: 'SI' , value: '+963', desc: 'Syria (+963)'},
        {countryCode: 'TW' , value: '+886', desc: 'Taiwan (+886)'},
        {countryCode: 'TJ' , value: '+7', desc: 'Tajikstan (+7)'},
        {countryCode: 'TH' , value: '+66', desc: 'Thailand (+66)'},
        {countryCode: 'TG' , value: '+228', desc: 'Togo (+228)'},
        {countryCode: 'TO' , value: '+676', desc: 'Tonga (+676)'},
        {countryCode: 'TT' , value: '+1868', desc: 'Trinidad &amp; Tobago (+1868)'},
        {countryCode: 'TN' , value: '+216', desc: 'Tunisia (+216)'},
        {countryCode: 'TR' , value: '+90', desc: 'Turkey (+90)'},
        {countryCode: 'TM' , value: '+7', desc: 'Turkmenistan (+7)'},
        {countryCode: 'TM' , value: '+993', desc: 'Turkmenistan (+993)'},
        {countryCode: 'TC' , value: '+1649', desc: 'Turks &amp; Caicos Islands (+1649)'},
        {countryCode: 'TV' , value: '+688', desc: 'Tuvalu (+688)'},
        {countryCode: 'UG' , value: '+256', desc: 'Uganda (+256)'},
        {countryCode: 'GB' , value: '+44', desc: 'UK (+44)'},
        {countryCode: 'UA' , value: '+380', desc: 'Ukraine (+380)'},
        {countryCode: 'AE' , value: '+971', desc: 'United Arab Emirates (+971)'},
        {countryCode: 'UY' , value: '+598', desc: 'Uruguay (+598)'},
        {countryCode: 'UZ' , value: '+7', desc: 'Uzbekistan (+7)'},
        {countryCode: 'VU' , value: '+678', desc: 'Vanuatu (+678)'},
        {countryCode: 'VA' , value: '+379', desc: 'Vatican City (+379)'},
        {countryCode: 'VE' , value: '+58', desc: 'Venezuela (+58)'},
        {countryCode: 'VN' , value: '+84', desc: 'Vietnam (+84)'},
        {countryCode: 'VG' , value: '+84', desc: 'Virgin Islands - British (+1284)'},
        {countryCode: 'VI' , value: '+84', desc: 'Virgin Islands - US (+1340)'},
        {countryCode: 'WF' , value: '+681', desc: 'Wallis &amp; Futuna (+681)'},
        {countryCode: 'YE' , value: '+969', desc: 'Yemen (North)(+969)'},
        {countryCode: 'YE' , value: '+967', desc: 'Yemen (South)(+967)'},
        {countryCode: 'ZM' , value: '+260', desc: 'Zambia (+260)'},
        {countryCode: 'ZW' , value: '+263', desc: 'Zimbabwe (+263)'},]; 
  
}